#include <iostream>
#include <vector>
#include <algorithm>
#include <exception>
using namespace std;


int main()
{
	vector<int> array(10, 42);
	try {
		array.at(10) = 10;
	}
	catch(const exception& e) {
		cout << "Exception: " << e.what() << endl;
	}
	return 0;
}